site_name: "Bioinformatics for Computational Genomics"
theme:
  name: mkdocs
  locale: en
  user_color_mode_toggle: true
  color_mode: light
markdown_extensions:
  - admonition
  - toc:
      permalink: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax-config.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - macros
  - awesome-pages:
      collapse_single_pages: false
repo_url: https://github.com/rhighs/bioinformatics-msc.git
nav:
  - Home: index.md
  - Resources: RESOURCES.md
  - Lectures:
      - Genetics: lectures/genetics-cellular-and-molecular-biology/index.md
      - Organic Chemistry: lectures/organic-chemistry/index.md
      - Biochemistry: lectures/biochemistry/index.md
      - Bioinformatics and Computational Biology: lectures/bioinformatics-and-computational-biology/index.md
      - Statistics: lectures/statistics/index.md
